'use client';
import { useEffect, useRef, useState } from 'react';
import { Box, Upload, Play, Pause, RotateCcw, Maximize, Download, Film, Layers, Eye, EyeOff, MoveUpRight, ChevronRight, LockKeyhole } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import type { Studio, PartInfo } from '@/lib/studio';
import { registerWorkspaceTools } from '@/lib/webmcp';
const modes = { radial: 'Radial', x: 'Along X', y: 'Along Y', z: 'Along Z' };
export default function Home() {
 const host=useRef<HTMLDivElement>(null),engine=useRef<Studio|null>(null),input=useRef<HTMLInputElement>(null);
 const [parts,setParts]=useState<PartInfo[]>([]),[selected,setSelected]=useState<number|null>(null);
 const [amount,setAmount]=useState(65),[playing,setPlaying]=useState(false),[mode,setMode]=useState('y'),[spread,setSpread]=useState(1),[duration,setDuration]=useState(6);
 const [labels,setLabels]=useState(false),[lines,setLines]=useState(true),[drawing,setDrawing]=useState(false),[filename,setFilename]=useState('Precision spindle');
 const [status,setStatus]=useState('Preparing workspace…'),[busy,setBusy]=useState(true),[error,setError]=useState(''),[recording,setRecording]=useState(false),[dragging,setDragging]=useState(false);
 const state=useRef({parts,amount,busy,recording});state.current={parts,amount,busy,recording};
 useEffect(()=>registerWorkspaceTools(()=>({parts:state.current.parts,amount:state.current.amount}),(value)=>{if(state.current.busy||state.current.recording||!engine.current)throw new Error('Workspace is busy.');engine.current.setAmount(value);setAmount(value);state.current.amount=value;return{amount:value,playing:false};}),[]);
 useEffect(()=>{let cancelled=false;import('@/lib/studio').then(async({Studio})=>{if(cancelled||!host.current)return;const s=new Studio(host.current,{onParts:setParts,onSelect:setSelected,onProgress:setAmount,onPlay:setPlaying});engine.current=s;await s.demo();if(!cancelled){setStatus('Ready · model stays on your device');setBusy(false);}}).catch(e=>{if(!cancelled){setError(e.message);setBusy(false);}});return()=>{cancelled=true;engine.current?.dispose();engine.current=null;};},[]);
 async function task(action:()=>Promise<void>,message:string){setBusy(true);setError('');setStatus(message);try{await action();setStatus('Ready · model stays on your device');}catch(e){setError(e instanceof Error?e.message:'Unable to complete this action.');setStatus('Action failed');}finally{setBusy(false);}}
 async function load(file?:File){if(!file||!engine.current||busy||recording)return;await task(async()=>{await engine.current!.load(file);setFilename(file.name);setSelected(null);setAmount(65);setPlaying(false);},'Reading model and separating parts…');}
 function chooseMode(v:string){void task(async()=>{await engine.current!.plan(v,spread);setMode(v);},'Calculating part positions…');}
 const active=parts.find(p=>p.id===selected);
 return <main className="studio-shell">
 <header className="topbar"><div className="brand"><span className="brand-icon"><Layers size={22}/></span><h1>explode<span>studio</span></h1><span className="beta">CAD WORKSPACE</span></div><div className="header-actions"><span className="privacy"><LockKeyhole size={13}/> Local processing</span><button className="primary" disabled={busy||recording} onClick={()=>input.current?.click()}><Upload size={16}/> Import model</button></div></header>
 <input ref={input} hidden type="file" accept=".step,.stp,.iges,.igs,.brep,.glb,.stl,.obj" onChange={e=>{void load(e.target.files?.[0]);e.target.value='';}}/>
 <div className="workspace"><aside className="assembly-panel"><div className="panel-title"><span>ASSEMBLY</span><span className="count">{parts.length}</span></div><div className="file-heading"><Box size={20}/><div><strong title={filename}>{filename}</strong><small>{filename==='Precision spindle'?'Example assembly':'Imported model'}</small></div></div>
 <button className="drop-button" disabled={busy||recording} onClick={()=>input.current?.click()}><Upload size={18}/><span>Open a CAD model<small>STEP, IGES, BREP, GLB, STL, OBJ · up to 50 MB</small></span></button><div className="parts-caption"><span>PARTS</span><span>Visibility</span></div>
 <div className="part-list">{parts.map((p,i)=><div key={p.id} className={'part-row '+(selected===p.id?'selected':'')}><button className="part-select" onClick={()=>engine.current?.select(p.id)}><span className="part-number">{String(i+1).padStart(2,'0')}</span><span className="color-dot" style={{background:p.color}}/><span title={p.name}>{p.name}</span></button><button className="icon-button" disabled={recording} aria-label={`${p.visible?'Hide':'Show'} ${p.name}`} onClick={()=>engine.current?.toggle(p.id)}>{p.visible?<Eye size={14}/>:<EyeOff size={14}/>}</button></div>)}</div>
 <div className="assembly-foot"><button className="text-button" disabled={busy||recording} onClick={()=>task(async()=>{await engine.current!.demo();setFilename('Precision spindle');setAmount(65);},'Loading example…')}><RotateCcw size={14}/> Load example</button><p>Assemblies need separate parts.<br/>A fused solid stays one part.</p></div></aside>
 <section className="viewport-panel" onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);void load(e.dataTransfer.files[0]);}} aria-label="3D assembly workspace">
 <div className="viewport-top"><div className="breadcrumb">Workspace <ChevronRight size={13}/><strong>Exploded view</strong></div><span className="live-dot">{drawing?'TECHNICAL':'SHADED'}</span></div><div ref={host} className="canvas-host" aria-label="Interactive 3D model. Drag to orbit, scroll to zoom, right-drag to pan."/>
 <div className="view-title"><span>ASSEMBLY STUDY / 001</span><h2>{filename.replace(/\.[^.]+$/,'')}</h2><p>{Math.round(amount)}% exploded</p></div><div className="viewport-tools"><button aria-label="Fit model" title="Fit model" onClick={()=>engine.current?.fit()}><Maximize size={18}/></button><button aria-label="Reset camera" title="Reset camera" onClick={()=>engine.current?.resetCamera()}><RotateCcw size={18}/></button></div>
 <div className="viewport-bottom"><span><i className="axis x"/> X <i className="axis y"/> Y <i className="axis z"/> Z</span><span>Drag to orbit · Scroll to zoom</span></div>{dragging&&<div className="drop-overlay">Drop your model here</div>}{busy&&<div className="loading"><span className="spinner"/>{status}</div>}{error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error">×</button></div>}
 <div className="timeline"><button className="play-button" aria-label={playing?'Pause animation':'Play animation'} disabled={busy||recording} onClick={()=>engine.current?.play()}>{playing?<Pause size={19}/>:<Play size={19}/>}</button><div className="scrubber"><div><span>Assembled</span><span>Exploded</span></div><Slider aria-label="Explosion amount" value={[amount]} min={0} max={100} step={.1} disabled={busy||recording} onValueChange={v=>{const n=Array.isArray(v)?v[0]:v;setAmount(n);engine.current?.setAmount(n);}}/></div><span className="timeline-value">{Math.round(amount)}<small>%</small></span></div></section>
 <aside className="settings-panel"><div className="panel-title"><span>EXPLOSION</span><MoveUpRight size={16}/></div><div className="settings-section"><h3>Make room for every part.</h3><p>Separate the assembly, then find your angle.</p><label className="field-label" id="direction-label">Direction</label><Select value={mode} onValueChange={v=>v&&chooseMode(v)} disabled={busy||recording}><SelectTrigger aria-labelledby="direction-label" className="wide"><SelectValue>{modes[mode as keyof typeof modes]}</SelectValue></SelectTrigger><SelectContent>{Object.entries(modes).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select>
 <div className="label-value"><label id="spacing-label">Spacing</label><span>{spread.toFixed(1)}×</span></div><Slider aria-labelledby="spacing-label" value={[spread]} min={.5} max={2.5} step={.1} disabled={busy||recording} onValueChange={v=>{const n=Array.isArray(v)?v[0]:v;setSpread(n);engine.current?.setSpread(n);}}/>
 <div className="label-value"><label id="duration-label">Cycle duration</label><span>{duration}s</span></div><Slider aria-labelledby="duration-label" value={[duration]} min={3} max={15} step={1} disabled={recording} onValueChange={v=>{const n=Array.isArray(v)?v[0]:v;setDuration(n);engine.current?.setDuration(n);}}/></div>
 <div className="settings-section"><div className="section-label">APPEARANCE</div>{[{label:'Part labels',checked:labels,fn:(v:boolean)=>{setLabels(v);engine.current?.appearance({labels:v});}},{label:'Guide lines',checked:lines,fn:(v:boolean)=>{setLines(v);engine.current?.appearance({lines:v});}},{label:'Technical drawing',checked:drawing,fn:(v:boolean)=>{setDrawing(v);engine.current?.appearance({drawing:v});}}].map(x=><div className="switch-row" key={x.label}><label htmlFor={x.label}>{x.label}</label><Switch id={x.label} checked={x.checked} disabled={recording} onCheckedChange={x.fn}/></div>)}</div>
 <div className="settings-section selected-part"><div className="section-label">SELECTED PART</div>{active?<><strong>{active.name}</strong><p>Adjust this part’s travel direction.</p><Select value={active.direction} disabled={busy||recording} onValueChange={v=>{if(v)void task(()=>engine.current!.direction(active.id,v),'Updating part direction…');}}><SelectTrigger aria-label="Selected part direction" className="wide"><SelectValue/></SelectTrigger><SelectContent>{[['auto','Automatic'],['fixed','Keep assembled'],['+x','+X'],['-x','−X'],['+y','+Y'],['-y','−Y'],['+z','+Z'],['-z','−Z']].map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></>:<p>Click a part in the model or assembly list to adjust its direction.</p>}</div>
 <div className="export-panel"><div className="section-label">EXPORT YOUR VIEW</div><button className="export-button" disabled={busy||recording} onClick={()=>{try{engine.current?.saveImage(filename);}catch(e){setError(String(e));}}}><Download size={16}/> Save drawing <span>PNG</span></button><button className="export-button" disabled={busy||recording} onClick={async()=>{setRecording(true);setError('');try{await engine.current?.saveVideo(filename);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setRecording(false);}}}><Film size={16}/>{recording?'Recording cycle…':'Save animation'}<span>VIDEO</span></button><small>Exports use the current view and visible parts.</small></div></aside></div>
 <footer className="statusbar"><span><span className="status-dot"/>{status}</span><span>Python + Three.js <span className="footer-divider">/</span> EXPLODE STUDIO</span></footer></main>;
}
