import * as T from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { demoParts, meshParts, cadParts, normalizeParts, type RawPart, type CadResult } from './models';
import { WorkerClient } from './worker-client';
export type PartInfo={id:number;name:string;color:string;visible:boolean;direction:string};
type Part=PartInfo&{mesh:T.Mesh<T.BufferGeometry,T.MeshStandardMaterial>;home:T.Vector3;size:T.Vector3;offset:T.Vector3;edge:T.LineSegments;guide:T.Line;label:T.Sprite};
type Callbacks={onParts:(parts:PartInfo[])=>void;onSelect:(id:number|null)=>void;onProgress:(v:number)=>void;onPlay:(v:boolean)=>void};
export class Studio {
 private renderer:T.WebGLRenderer;private scene=new T.Scene();private camera=new T.PerspectiveCamera(35,1,.01,2000);private controls:OrbitControls;private root=new T.Group();private parts:Part[]=[];
 private planner=new WorkerClient('/workers/planner.mjs',true);private cad=new WorkerClient('/workers/cad.js');private observer:ResizeObserver;private env:T.WebGLRenderTarget;
 private amount=65;private spread=1;private duration=6;private playing=false;private phase=0;private last=0;private frame=0;private lastNotify=0;private mode='y';private selected:number|null=null;private showLabels=false;private showLines=true;private drawing=false;private disposed=false;private recording=false;private recorder:MediaRecorder|null=null;
 constructor(private host:HTMLElement,private cb:Callbacks){
  try{this.renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});}catch{throw new Error('This browser could not start WebGL. Enable hardware acceleration or try another browser.');}
  this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setClearColor(0xf2f5f2,0);this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.35;
  host.appendChild(this.renderer.domElement);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.minDistance=.2;this.controls.maxDistance=500;
  const room=new RoomEnvironment(),pmrem=new T.PMREMGenerator(this.renderer);this.env=pmrem.fromScene(room,.04);this.scene.environment=this.env.texture;room.dispose();pmrem.dispose();
  this.scene.add(new T.HemisphereLight(0xffffff,0x9aafa0,2.2));const light=new T.DirectionalLight(0xffffff,3);light.position.set(3,8,5);this.scene.add(light,this.root);
  this.camera.position.set(9,6,10);this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(host);this.resize();
  let start=new T.Vector2();this.renderer.domElement.addEventListener('pointerdown',e=>{start.set(e.clientX,e.clientY);});this.renderer.domElement.addEventListener('pointerup',e=>{if(start.distanceTo(new T.Vector2(e.clientX,e.clientY))>4)return;const r=host.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),this.camera);const hit=ray.intersectObjects(this.parts.filter(p=>p.visible).map(p=>p.mesh),false)[0];this.select(hit?Number(hit.object.userData.id):null);});
  this.frame=requestAnimationFrame(this.tick);
 }
 private resize(){if(this.recording)return;const w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 private tick=(time:number)=>{if(this.disposed)return;const dt=this.last?Math.min((time-this.last)/1000,.1):0;this.last=time;if(this.playing&&!document.hidden){this.phase=(this.phase+dt/this.duration)%1;this.amount=(1-Math.cos(this.phase*Math.PI*2))*50;if(time-this.lastNotify>60){this.cb.onProgress(this.amount);this.lastNotify=time;}}this.apply();this.controls.update();this.renderer.render(this.scene,this.camera);this.frame=requestAnimationFrame(this.tick);};
 private info(){this.cb.onParts(this.parts.map(({id,name,color,visible,direction})=>({id,name,color,visible,direction})));}
 private clear(){for(const p of this.parts){p.mesh.geometry.dispose();p.mesh.material.dispose();p.edge.geometry.dispose();(p.edge.material as T.Material).dispose();p.guide.geometry.dispose();(p.guide.material as T.Material).dispose();p.label.material.map?.dispose();p.label.material.dispose();}this.root.clear();this.parts=[];}
 private makeLabel(index:number,name:string){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=80;const c=canvas.getContext('2d')!;c.fillStyle='#ffffffed';c.beginPath();c.roundRect(0,0,512,80,12);c.fill();c.fillStyle='#315844';c.font='25px Arial';c.fillText(`${String(index+1).padStart(2,'0')}  ${name.slice(0,28)}`,18,49);const texture=new T.CanvasTexture(canvas);texture.colorSpace=T.SRGBColorSpace;const sprite=new T.Sprite(new T.SpriteMaterial({map:texture,depthTest:false}));sprite.scale.set(1.7,.266,1);sprite.renderOrder=10;return sprite;}
 private async replace(raw:RawPart[]){
  try{normalizeParts(raw);}catch(e){raw.forEach(p=>p.geometry.dispose());throw e;}
  const bounds=raw.map(p=>({center:p.geometry.boundingBox!.getCenter(new T.Vector3()).toArray(),size:p.geometry.boundingBox!.getSize(new T.Vector3()).toArray(),direction:'auto'}));
  let plan:{offsets:number[][]};try{plan=await this.planner.request({parts:bounds,mode:this.mode});}catch(e){raw.forEach(p=>p.geometry.dispose());throw e;}
  if(this.disposed){raw.forEach(p=>p.geometry.dispose());return;}
  this.playing=false;this.cb.onPlay(false);this.clear();
  this.parts=raw.map((raw,i)=>{const home=new T.Vector3().fromArray(bounds[i].center),size=new T.Vector3().fromArray(bounds[i].size);raw.geometry.translate(-home.x,-home.y,-home.z);const material=new T.MeshStandardMaterial({color:raw.color,metalness:.55,roughness:.32,side:T.DoubleSide});const mesh=new T.Mesh(raw.geometry,material);mesh.userData.id=i;const edge=new T.LineSegments(new T.EdgesGeometry(raw.geometry,28),new T.LineBasicMaterial({color:0x3a594a,transparent:true,opacity:.22}));mesh.add(edge);const guide=new T.Line(new T.BufferGeometry().setFromPoints([home,home]),new T.LineDashedMaterial({color:0x90aa99,dashSize:.07,gapSize:.06,transparent:true,opacity:.55}));const label=this.makeLabel(i,raw.name);this.root.add(mesh,guide,label);return{id:i,name:raw.name,color:'#'+raw.color.getHexString(),visible:true,direction:'auto',mesh,home,size,offset:new T.Vector3().fromArray(plan.offsets[i]),edge,guide,label};});
  this.amount=65;this.select(null);this.info();this.appearance({});this.fit(true);this.cb.onProgress(this.amount);
 }
 async demo(){await this.replace(demoParts());}
 async load(file:File){if(file.size>50*1024*1024)throw new Error('Choose a model smaller than 50 MB.');if(file.size===0)throw new Error('This file is empty.');const ext=file.name.split('.').pop()?.toLowerCase()??'';if(!['step','stp','iges','igs','brep','glb','stl','obj'].includes(ext))throw new Error('Use STEP, IGES, BREP, GLB, STL or OBJ. Native CAD files must be exported first.');let raw:RawPart[];if(['step','stp','iges','igs','brep'].includes(ext)){const buffer=await file.arrayBuffer();raw=cadParts(await this.cad.request<CadResult>({ext,buffer},[buffer]));}else raw=await meshParts(file);await this.replace(raw);}
 async plan(mode=this.mode,spread=this.spread){const result=await this.planner.request<{offsets:number[][]}>({mode,parts:this.parts.map(p=>({center:p.home.toArray(),size:p.size.toArray(),direction:p.direction}))});if(this.disposed)return;this.mode=mode;this.spread=spread;this.parts.forEach((p,i)=>p.offset.fromArray(result.offsets[i]));this.apply();this.fit(true);}
 async direction(id:number,direction:string){const part=this.parts.find(p=>p.id===id);if(!part)return;const previous=part.direction;part.direction=direction;try{await this.plan();this.info();}catch(e){part.direction=previous;throw e;}}
 setSpread(value:number){this.spread=value;this.apply();this.fit(true);}
 setDuration(value:number){this.duration=value;}
 setAmount(value:number){this.playing=false;this.cb.onPlay(false);this.amount=T.MathUtils.clamp(value,0,100);this.apply();}
 play(){if(this.recording)return;this.playing=!this.playing;this.phase=Math.acos(1-this.amount/50)/(2*Math.PI);this.cb.onPlay(this.playing);}
 select(id:number|null){this.selected=id;this.cb.onSelect(id);for(const p of this.parts)p.mesh.material.emissive.setHex(p.id===id?0x164d35:0);}
 toggle(id:number){const p=this.parts.find(p=>p.id===id);if(p){p.visible=!p.visible;this.apply();this.info();}}
 appearance(options:{labels?:boolean;lines?:boolean;drawing?:boolean}){this.showLabels=options.labels??this.showLabels;this.showLines=options.lines??this.showLines;this.drawing=options.drawing??this.drawing;for(const p of this.parts){p.mesh.material.color.set(this.drawing?'#ffffff':p.color);p.mesh.material.metalness=this.drawing?0:.55;p.mesh.material.roughness=this.drawing?1:.32;(p.edge.material as T.LineBasicMaterial).opacity=this.drawing?.8:.22;}this.apply();}
 private apply(){const t=this.amount/100;for(const p of this.parts){p.mesh.position.copy(p.home).addScaledVector(p.offset,t*this.spread);p.mesh.visible=p.visible;p.label.visible=p.visible&&this.showLabels;p.label.position.copy(p.mesh.position).add(new T.Vector3(p.size.x/2+.85,0,0));p.guide.visible=p.visible&&this.showLines&&t>.01;const a=p.guide.geometry.getAttribute('position') as T.BufferAttribute;a.setXYZ(0,p.home.x,p.home.y,p.home.z);a.setXYZ(1,p.mesh.position.x,p.mesh.position.y,p.mesh.position.z);a.needsUpdate=true;p.guide.geometry.computeBoundingSphere();p.guide.computeLineDistances();}}
 fit(full=false){const box=new T.Box3();for(const p of this.parts){if(!p.visible)continue;for(const t of full?[0,1]:[this.amount/100]){const c=p.home.clone().addScaledVector(p.offset,t*this.spread);box.union(new T.Box3().setFromCenterAndSize(c,p.size));}}if(box.isEmpty())return;const center=box.getCenter(new T.Vector3()),radius=box.getSize(new T.Vector3()).length()/2;const fov=T.MathUtils.degToRad(this.camera.fov),limiting=2*Math.atan(Math.tan(fov/2)*Math.min(1,this.camera.aspect));const distance=Math.max(2,radius/Math.sin(limiting/2)*1.15);const direction=this.camera.position.clone().sub(this.controls.target).normalize();this.controls.target.copy(center);this.camera.position.copy(center).addScaledVector(direction,distance);this.camera.far=Math.max(2000,distance*5);this.camera.updateProjectionMatrix();this.controls.update();}
 resetCamera(){this.camera.position.copy(this.controls.target).add(new T.Vector3(9,6,10));this.fit(true);}
 private download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name.replace(/[<>:"/\\|?*]/g,'_');a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 saveImage(name:string){const old=this.scene.background;this.scene.background=new T.Color('#f3f6f3');this.renderer.render(this.scene,this.camera);this.renderer.domElement.toBlob(blob=>{if(blob)this.download(blob,name.replace(/\.[^.]+$/,'')+'-exploded.png');},'image/png');this.scene.background=old;}
 async saveVideo(name:string){
  if(typeof MediaRecorder==='undefined'||!this.renderer.domElement.captureStream)throw new Error('Video export is unavailable in this browser. Use a current Chrome, Edge or Firefox browser.');
  const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/mp4'].find(x=>MediaRecorder.isTypeSupported(x));if(!mime)throw new Error('This browser has no supported video encoder. Save a PNG or try another browser.');
  const previous={amount:this.amount,playing:this.playing,background:this.scene.background};this.playing=false;this.cb.onPlay(false);this.recording=true;this.controls.enabled=false;this.scene.background=new T.Color('#f3f6f3');const stream=this.renderer.domElement.captureStream(30);const recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:8000000});this.recorder=recorder;const chunks:Blob[]=[];let frame=0;
  try{await new Promise<void>((resolve,reject)=>{recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onerror=()=>reject(new Error('The video encoder failed. Try a shorter recording.'));recorder.onstop=()=>{if(this.disposed)reject(new Error('Workspace closed.'));else resolve();};this.amount=0;this.apply();this.renderer.render(this.scene,this.camera);recorder.start(100);const start=performance.now();const record=(now:number)=>{const t=Math.min(1,(now-start)/(this.duration*1000));this.amount=(1-Math.cos(t*Math.PI*2))*50;this.cb.onProgress(this.amount);if(t<1&&!this.disposed)frame=requestAnimationFrame(record);else if(recorder.state!=='inactive')recorder.stop();};frame=requestAnimationFrame(record);});if(!chunks.length)throw new Error('The video encoder produced an empty file.');this.download(new Blob(chunks,{type:mime}),name.replace(/\.[^.]+$/,'')+'-exploded.'+(mime.startsWith('video/mp4')?'mp4':'webm'));}
  finally{cancelAnimationFrame(frame);if(recorder.state!=='inactive')recorder.stop();stream.getTracks().forEach(t=>t.stop());this.recorder=null;this.recording=false;this.controls.enabled=true;this.amount=previous.amount;this.playing=previous.playing;this.scene.background=previous.background;this.cb.onProgress(this.amount);this.cb.onPlay(this.playing);this.resize();}
 }
 dispose(){this.disposed=true;cancelAnimationFrame(this.frame);if(this.recorder?.state==='recording')this.recorder.stop();this.observer.disconnect();this.controls.dispose();this.clear();this.env.dispose();this.renderer.dispose();this.renderer.domElement.remove();this.planner.dispose();this.cad.dispose();}
}
